//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primerr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Animal.
    /// </summary>
    // *** Start programmer edit section *** (Animal CustomAttributes)

    // *** End programmer edit section *** (Animal CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AnimalE", new string[] {
            "Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("AnimalE", "Burrow", "BurrowE", true, "", "Burrow", true, new string[] {
            ""})]
    [View("AnimalL", new string[] {
            "Name as \'Name\'"})]
    public class Animal : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Primerr.DetailArrayOfBurrow fBurrow;
        
        // *** Start programmer edit section *** (Animal CustomMembers)

        // *** End programmer edit section *** (Animal CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Animal.Name CustomAttributes)

        // *** End programmer edit section *** (Animal.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Animal.Name Get start)

                // *** End programmer edit section *** (Animal.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Animal.Name Get end)

                // *** End programmer edit section *** (Animal.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Animal.Name Set start)

                // *** End programmer edit section *** (Animal.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Animal.Name Set end)

                // *** End programmer edit section *** (Animal.Name Set end)
            }
        }
        
        /// <summary>
        /// Animal.
        /// </summary>
        // *** Start programmer edit section *** (Animal.Burrow CustomAttributes)

        // *** End programmer edit section *** (Animal.Burrow CustomAttributes)
        public virtual IIS.Primerr.DetailArrayOfBurrow Burrow
        {
            get
            {
                // *** Start programmer edit section *** (Animal.Burrow Get start)

                // *** End programmer edit section *** (Animal.Burrow Get start)
                if ((this.fBurrow == null))
                {
                    this.fBurrow = new IIS.Primerr.DetailArrayOfBurrow(this);
                }
                IIS.Primerr.DetailArrayOfBurrow result = this.fBurrow;
                // *** Start programmer edit section *** (Animal.Burrow Get end)

                // *** End programmer edit section *** (Animal.Burrow Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Animal.Burrow Set start)

                // *** End programmer edit section *** (Animal.Burrow Set start)
                this.fBurrow = value;
                // *** Start programmer edit section *** (Animal.Burrow Set end)

                // *** End programmer edit section *** (Animal.Burrow Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AnimalE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalE", typeof(IIS.Primerr.Animal));
                }
            }
            
            /// <summary>
            /// "AnimalL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AnimalL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AnimalL", typeof(IIS.Primerr.Animal));
                }
            }
        }
    }
}
