//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primerr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Forest.
    /// </summary>
    // *** Start programmer edit section *** (Forest CustomAttributes)

    // *** End programmer edit section *** (Forest CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ForestE", new string[] {
            "Name as \'Name\'",
            "Coordinates as \'Coor\'"})]
    [View("ForestL", new string[] {
            "Name as \'Name\'",
            "Coordinates as \'Coordinates\'"})]
    public class Forest : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fCoordinates;
        
        private IIS.Primerr.Country fCountry;
        
        // *** Start programmer edit section *** (Forest CustomMembers)

        // *** End programmer edit section *** (Forest CustomMembers)

        
        /// <summary>
        /// Coordinates.
        /// </summary>
        // *** Start programmer edit section *** (Forest.Coordinates CustomAttributes)

        // *** End programmer edit section *** (Forest.Coordinates CustomAttributes)
        [StrLen(255)]
        public virtual string Coordinates
        {
            get
            {
                // *** Start programmer edit section *** (Forest.Coordinates Get start)

                // *** End programmer edit section *** (Forest.Coordinates Get start)
                string result = this.fCoordinates;
                // *** Start programmer edit section *** (Forest.Coordinates Get end)

                // *** End programmer edit section *** (Forest.Coordinates Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Forest.Coordinates Set start)

                // *** End programmer edit section *** (Forest.Coordinates Set start)
                this.fCoordinates = value;
                // *** Start programmer edit section *** (Forest.Coordinates Set end)

                // *** End programmer edit section *** (Forest.Coordinates Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Forest.Name CustomAttributes)

        // *** End programmer edit section *** (Forest.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Forest.Name Get start)

                // *** End programmer edit section *** (Forest.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Forest.Name Get end)

                // *** End programmer edit section *** (Forest.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Forest.Name Set start)

                // *** End programmer edit section *** (Forest.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Forest.Name Set end)

                // *** End programmer edit section *** (Forest.Name Set end)
            }
        }
        
        /// <summary>
        /// Forest.
        /// </summary>
        // *** Start programmer edit section *** (Forest.Country CustomAttributes)

        // *** End programmer edit section *** (Forest.Country CustomAttributes)
        [PropertyStorage(new string[] {
                "Country"})]
        public virtual IIS.Primerr.Country Country
        {
            get
            {
                // *** Start programmer edit section *** (Forest.Country Get start)

                // *** End programmer edit section *** (Forest.Country Get start)
                IIS.Primerr.Country result = this.fCountry;
                // *** Start programmer edit section *** (Forest.Country Get end)

                // *** End programmer edit section *** (Forest.Country Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Forest.Country Set start)

                // *** End programmer edit section *** (Forest.Country Set start)
                this.fCountry = value;
                // *** Start programmer edit section *** (Forest.Country Set end)

                // *** End programmer edit section *** (Forest.Country Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ForestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ForestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ForestE", typeof(IIS.Primerr.Forest));
                }
            }
            
            /// <summary>
            /// "ForestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ForestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ForestL", typeof(IIS.Primerr.Forest));
                }
            }
        }
    }
}
